name: Update posts

on:
#  push:
#    branches:
#      - master
  schedule:
    - cron: '29,59 * * * *'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get latest pots
        run: go run ./cmd/main.go

      - name: Auto commit action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update database
          branch: master

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          # https://github.com/enriikke/gatsby-gh-pages-action/issues/27
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths

